In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
df = pd.read_csv("loan_data_set.csv")
df.head(15)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N
10,LP001024,Male,Yes,2,Graduate,No,3200,700.0,70.0,360.0,1.0,Urban,Y
11,LP001027,Male,Yes,2,Graduate,NaN,2500,1840.0,109.0,360.0,1.0,Urban,Y
12,LP001028,Male,Yes,2,Graduate,No,3073,8106.0,200.0,360.0,1.0,Urban,Y
13,LP001029,Male,No,0,Graduate,No,1853,2840.0,114.0,360.0,1.0,Rural,N
14,LP001030,Male,Yes,2,Graduate,No,1299,1086.0,17.0,120.0,1.0,Urban,Y

In [37]:
#Basic information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [39]:
#Brief summary on NaN values pattern, frequency
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [41]:
#Fill in NaN values in Gender column by selecting most frequency of status: Male, Female → The first one with modifying.
#df["Gender"].fillna(df["Gender"].mode()[0], inplace = True)

In [57]:
#Convert from categorical data into numerical groups (In this case we have Genders and Married are two categorical ones)
categorical_columns = ["Gender", "Married", "Education", "Self_Employed", "Loan_Status"]
encoded_data = df[categorical_columns]
encoded_data.fillna("None")

     Gender Married     Education Self_Employed Loan_Status
0      Male      No      Graduate            No           Y
1      Male     Yes      Graduate            No           N
2      Male     Yes      Graduate           Yes           Y
3      Male     Yes  Not Graduate            No           Y
4      Male      No      Graduate            No           Y
..      ...     ...           ...           ...         ...
609  Female      No      Graduate            No           Y
610    Male     Yes      Graduate            No           Y
611    Male     Yes      Graduate            No           Y
612    Male     Yes      Graduate            No           Y
613  Female      No      Graduate           Yes           N

[614 rows x 5 columns]

In [59]:
#Thus, for each sub-classification of Gender, Married groups, add behind the underscore the categorical variables
pd.get_dummies(encoded_data)

,Gender_Female,Gender_Male,Married_No,Married_Yes,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Loan_Status_N,Loan_Status_Y
0,False,True,True,False,True,False,True,False,False,True
1,False,True,False,True,True,False,True,False,True,False
2,False,True,False,True,True,False,False,True,False,True
3,False,True,False,True,False,True,True,False,False,True
4,False,True,True,False,True,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...
609,True,False,True,False,True,False,True,False,False,True
610,False,True,False,True,True,False,True,False,False,True
611,False,True,False,True,True,False,True,False,False,True
612,False,True,False,True,True,False,True,False,False,True
613,True,False,True,False,True,False,False,True,True,False

In [61]:
#Information on types of encoded_data
pd.get_dummies(encoded_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Gender_Female           614 non-null    bool
 1   Gender_Male             614 non-null    bool
 2   Married_No              614 non-null    bool
 3   Married_Yes             614 non-null    bool
 4   Education_Graduate      614 non-null    bool
 5   Education_Not Graduate  614 non-null    bool
 6   Self_Employed_No        614 non-null    bool
 7   Self_Employed_Yes       614 non-null    bool
 8   Loan_Status_N           614 non-null    bool
 9   Loan_Status_Y           614 non-null    bool
dtypes: bool(10)
memory usage: 6.1 KB

In [63]:
#Alternative to Pandas: Sci-kit Learn, One-hot encoders
from sklearn.preprocessing import OneHotEncoder

By adding drop = "first" into One Hot Encoder function, we should avoid the Dummy Variable Trap (Redundancy and Multicollinearity).

### Dummy Variable Trap ###
A situation where one feature can be perfectly predicted using the others. This causes problems in linear models (like Linear or Logistic Regression), where this kind of perfect multicollinearity can lead to:
- Incorrect coefficient estimation
- Model instability

#### "Unothordox - More is not always better - It's about the independece of the features, not just their numbers" ####

In [69]:
#ohe = OneHotEncoder(drop = "first", sparse_output = False)
ohe = OneHotEncoder(sparse_output = False)
one_hot_encoded = ohe.fit_transform(encoded_data)
ohe_df = pd.DataFrame(one_hot_encoded, columns = ohe.get_feature_names_out(categorical_columns))

In [73]:
df_sklearn_encoded = pd.concat([df.drop(categorical_columns, axis = 1), ohe_df], axis = 1)
df_sklearn_encoded

,Loan_ID,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Gender_Female,Gender_Male,...,Married_No,Married_Yes,Married_nan,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Self_Employed_nan,Loan_Status_N,Loan_Status_Y
0,LP001002,0,5849,0.0,NaN,360.0,1.0,Urban,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
1,LP001003,1,4583,1508.0,128.0,360.0,1.0,Rural,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,LP001005,0,3000,0.0,66.0,360.0,1.0,Urban,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
3,LP001006,0,2583,2358.0,120.0,360.0,1.0,Urban,0.0,1.0,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
4,LP001008,0,6000,0.0,141.0,360.0,1.0,Urban,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,0,2900,0.0,71.0,360.0,1.0,Rural,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
610,LP002979,3+,4106,0.0,40.0,180.0,1.0,Rural,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
611,LP002983,1,8072,240.0,253.0,360.0,1.0,Urban,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
612,LP002984,2,7583,0.0,187.0,360.0,1.0,Urban,0.0,1.0,...,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
613,LP002990,0,4583,0.0,133.0,360.0,0.0,Semiurban,1.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0